version: "3"

services:

  flask:
    build:
      context: ./flask
      dockerfile: Dockerfile
    volumes:
      - ./flask:/opt
      - /var/run/docker.sock:/run/docker.sock:ro  # macOS hosts (Comment/delete if on Unix)
#      - /run/docker.sock:/run/docker.sock:ro      # Unix hosts (Uncomment if required)
    expose:
      - "5000"

  nginx:
    image: nginx:1.20-alpine
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:8080"
    depends_on:
      - "flask"